const cities = [
    { value: 0, label: "All" },
    { value: 1, label: "Casablanca" },
    { value: 2, label: "Fez" },
    { value: 3, label: "Rabat" },
    { value: 4, label: "Tangier" },
    { value: 5, label: "Marrakesh" },
    { value: 6, label: "Agadir" },
    { value: 7, label: "Salé" },
    { value: 8, label: "Oujda" },
    { value: 9, label: "Khouribga" },
    { value: 10, label: "Meknes" },
    { value: 11, label: "Kenitra" },
    { value: 12, label: "Tetouan" },
    { value: 13, label: "Safi" },
    { value: 14, label: "Temara" },
    { value: 15, label: "Mohammedia" },
    { value: 16, label: "El Jadida" },
    { value: 17, label: "Beni Mellal" },
    { value: 18, label: "Aït Melloul" },
    { value: 19, label: "Nador" },
    { value: 20, label: "Dar Bouazza" },
    { value: 21, label: "Taza" },
    { value: 22, label: "Settat" },
    { value: 23, label: "Berrechid" },
    { value: 24, label: "Khemisset" },
    { value: 25, label: "Inezgane" },
    { value: 26, label: "Ksar El Kebir" },
    { value: 27, label: "Larache" },
    { value: 28, label: "Guelmim" },
    { value: 29, label: "Khenifra" },
    { value: 30, label: "Berkane" },
    { value: 31, label: "Taourirt" },
    { value: 32, label: "Bouskoura" },
    { value: 33, label: "Fquih Ben Salah" },
    { value: 34, label: "Dcheira El Jihadia" },
    { value: 35, label: "Oued Zem" },
    { value: 36, label: "El Kelaa Des Sraghna" },
    { value: 37, label: "Sidi Slimane" },
    { value: 38, label: "Errachidia" },
    { value: 39, label: "Guercif" },
    { value: 40, label: "Oulad Teima" },
    { value: 41, label: "Ben Guerir" },
    { value: 42, label: "Tifelt" },
    { value: 43, label: "Lqliaa" },
    { value: 44, label: "Taroudant" },
    { value: 45, label: "Sefrou" },
    { value: 46, label: "Essaouira" },
    { value: 47, label: "Fnideq" },
    { value: 48, label: "Sidi Kacem" },
    { value: 49, label: "Tiznit" },
    { value: 50, label: "Tan-Tan" },
    { value: 51, label: "Ouarzazate" },
    { value: 52, label: "Souk El Arbaa" },
    { value: 53, label: "Youssoufia" },
    { value: 54, label: "Lahraouyine" },
    { value: 55, label: "Martil" },
    { value: 56, label: "Ain Harrouda" },
    { value: 57, label: "Suq as-Sabt Awlad an-Nama" },
    { value: 58, label: "Skhirat" },
    { value: 59, label: "Ouazzane" },
    { value: 60, label: "Benslimane" },
    { value: 61, label: "Al Hoceima" },
    { value: 62, label: "Beni Ansar" },
    { value: 63, label: "M'diq" },
    { value: 64, label: "Sidi Bennour" },
    { value: 65, label: "Midelt" },
    { value: 66, label: "Azrou" },
    { value: 67, label: "Drargua" }
  ];

  export default cities;
  